import BaseLayout from "@/components/layout/BaseLayout";
import "./globals.css";
import { AuthProvider } from "@/components/authProvider";
import { ThemeProvider } from "@/components/themeProvider";
import { cn } from "@/lib/utils";

import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <AuthProvider>
            <BaseLayout
              className={
                "flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col bg-muted/40"
              }
            >
              {children}
            </BaseLayout>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
